### PR TITLE
Fixed bumblebee overlay browse functionality for the document extjs listings

### LINKED ISSUE #1872: Neue Dokumente abholen in Listenansicht
In der Listenansicht kann im Overlay momentan nur durch aktuell angezeigte Dokumente navigiert werden.

Sind mehr Dokumente vorhanden als der aktuelle Batch, muss der Showroom die Möglichkeit haben, neue Dokumente abzuholen sobald dieser das letzte Dokument erreicht.

Dies kann mit der Tail-Funktion erreicht werden: https://github.com/4teamwork/opengever.core/blob/master/opengever/bumblebee/browser/resources/bumblebee.js#L41

Die Fetch-Url kann mittels `store.proxy.url` von der Tabbedview abgeholt werden. Die URL muss noch ein wenig zugeschnitten werden. So muss der `pagenumber`-Parameter in der Url jeweils korrekt angegeben werden. Zusätzlich muss der parameter `tableType=extjs` angehängt werden damit wir nicht die komplette Seite erhalten sondern nur die HTML-Fragmente der Dokumente.

### PR DESCRIPTION
**Pull request by phgross**
Fixes #1872 by implementing a special handling for extjs listing tabs in the `tail` and `head` methods, which loads and extend the next or previous batch to the showroom queue.

⚠️  Uses https://github.com/4teamwork/ftw.showroom/pull/29

@deiferni or @bierik please have a 👀

### CODE REVIEW

File: opengever/bumblebee/browser/resources/bumblebee.js [hunk 1]
```diff
@@ -26,6 +26,38 @@
...
+      }));
+    });
+
+  }
+
+  function loadNextListingItems() {
+    var pagenumber = global.tabbedview.param('pagenumber:int');
+    if (!pagenumber) {
+      pagenumber = 1;
+    }
```
Comment (bierik) [inline opengever/bumblebee/browser/resources/bumblebee.js]: `var pagenumber = global.tabbedview.param('pagenumber:int') || 1;` would be much more simpler.

File: opengever/bumblebee/browser/resources/bumblebee.js [hunk 2]
```diff
@@ -26,6 +26,38 @@
...
+
+    extendShowroomQueue(pagenumber + 1, showroom.append);
```
Comment (bierik) [inline opengever/bumblebee/browser/resources/bumblebee.js]: Why do you increment the pagenumber twice? -> https://github.com/4teamwork/opengever.core/pull/1954/files#diff-3cb0067a300ed87ae7e8ab9f9c0b8ad0R31

File: opengever/bumblebee/browser/resources/bumblebee.js [hunk 3]
```diff
@@ -40,12 +72,25 @@
 
   function tail() {
     if(global.tabbedview) {
+      if (global.tabbedview.table.length) {
```
Comment (bierik) [inline opengever/bumblebee/browser/resources/bumblebee.js]: `if(global.tabbedview && global.tabbedview.table.length)` would be much more simpler.

File: opengever/bumblebee/browser/resources/bumblebee.js [hunk 4]
```diff
@@ -40,12 +72,25 @@
...
+        // document table listing
+        loadNextListingItems();
+      }
       loadNextTabbedviewItems();
     }
   }
 
+  function head() {
+    if(global.tabbedview) {
+      if (global.tabbedview.table.length) {
```
Comment (bierik) [inline opengever/bumblebee/browser/resources/bumblebee.js]: `if(global.tabbedview && global.tabbedview.table.length)` would be much more simpler

**Comment by phgross** [comment]
@deiferni or @bierik updated ...
