### PR TITLE
Fix removal of agenda items

### LINKED ISSUE #3407: Freitext Traktandum kann nicht mehr gelöscht werden
Der Confirmation-Dialog wird zwar angezeigt, anschliessend kommt es aber zu einem JS Fehler. Die Entfernung des Traktandums im Backend würde aber funktionieren.
```
resourceopengever.basenotify-cachekey-13ac28b28181a3b200e2b62cee5f0745.js:4905 Uncaught TypeError: Cannot read property 'close' of undefined
    at AgendaItemController.closeModal (resourceopengever.basenotify-cachekey-13ac28b28181a3b200e2b62cee5f0745.js:4905)
    at AgendaItemController.unschedule (resourceopengever.basenotify-cachekey-13ac28b28181a3b200e2b62cee5f0745.js:4905)
    at AgendaItemController.Controller.trackEvent (resourceopengever.basenotify-cachekey-13ac28b28181a3b200e2b62cee5f0745.js:4802)
    at HTMLButtonElement.<anonymous> (resourceopengever.basenotify-cachekey-13ac28b28181a3b200e2b62cee5f0745.js:4804)
    at HTMLDocument.dispatch (resourceplone.app.jquery-cachekey-f42bfbe37a1980083336aefe116bb531.js:13)
    at HTMLDocument.r.handle (resourceplone.app.jquery-cachekey-f42bfbe37a1980083336aefe116bb531.js:13)
```

Bsp. https://dev.onegovgever.ch/fd/sitzungen/committee-8/meeting-41/view

### PR DESCRIPTION
**Pull request by tarnap**
Some modals (dialogs) exist only in the no-word version.
Trying to close them leads to a javascript error.
Make sure the dialogs are not undefined before trying to close them.

Resolves #3407 

Needs backport to: `2017.5-stable`

### CODE REVIEW

File: opengever/meeting/browser/resources/meeting.js [hunk 1]
```diff
@@ -183,8 +183,12 @@
     this.closeModal = function() {
       unscheduleDialog.close();
       deleteDialog.close();
-      returnExcerptDialog.close();
-      createExcerptDialog.close();
+      if (typeof(returnExcerptDialog) !== 'undefined') {
+        returnExcerptDialog.close();
+      }
+      if (typeof(createExcerptDialog) !== 'undefined') {
```
Comment (jone) [inline opengever/meeting/browser/resources/meeting.js]: Am I understanding this correctly?
The problem is that when there is no `#confirm_create_excerpt` node, the variable `createExcerptDialog` will be `undefined` because.
Since we have two templates, either `#confirm_create_excerpt`, `#confirm_return_excerpt` is present.

Comment (tarnap) [reply opengever/meeting/browser/resources/meeting.js]: @jone: The way I see it is as follows:
The controllers in `o/m/b/r/meeting.js` tries to generate overlays using IDs.
If  a div (or other DOM element) exists with the given id, an overlay is generated, else the overlay is not created and the method `close` cannot be called.

returnExcerptDialog and createExcerptDialog are only created when the word feature is enabled since the id's of these two dialogs exist only in word templates:

```
(spv) ~/p/spv ❯❯❯ grep -ri "confirm_create_excerpt" opengever                                                   pv-fix_removing_agenda_items ◼ 
opengever/meeting/browser/meetings/templates/meeting-word.pt:        <div class="overlay" id="confirm_create_excerpt">                         
opengever/meeting/browser/meetings/templates/meeting-word.pt:          <p i18n:translate="msg_confirm_create_excerpt_dialog">                  
opengever/meeting/browser/resources/meeting.js:    var createExcerptDialog = $('#confirm_create_excerpt').overlay({                            
opengever/meeting/browser/resources/meeting.js:      return $.post(link, $('#confirm_create_excerpt form').serialize())                        
opengever/meeting/browser/resources/meeting.js:        target: "#confirm_create_excerpt .confirm",                                             
opengever/meeting/browser/resources/meeting.js:        target: "#confirm_unschedule .decline, #confirm_delete .decline, #confirm_return_excerpt .decline, #confirm_create_excerpt .decline",
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po:msgid "msg_confirm_create_excerpt_dialog"                                        
Binary file opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.mo matches                                                              
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po:msgid "msg_confirm_create_excerpt_dialog"                                        
opengever/meeting/locales/opengever.meeting.pot:msgid "msg_confirm_create_excerpt_dialog"                                                      
(spv) ~/p/spv ❯❯❯ grep -ri "confirm_return_excerpt" opengever                                                   pv-fix_removing_agenda_items ◼ 
opengever/meeting/browser/meetings/templates/meeting-word.pt:        <div class="overlay" id="confirm_return_excerpt">                         
opengever/meeting/browser/meetings/templates/meeting-word.pt:          <p i18n:translate="msg_confirm_return_excerpt_dialog">                  
opengever/meeting/browser/resources/meeting.js:    var returnExcerptDialog = $("#confirm_return_excerpt").overlay({                            
opengever/meeting/browser/resources/meeting.js:        target: "#confirm_return_excerpt .confirm",                                             
opengever/meeting/browser/resources/meeting.js:        target: "#confirm_unschedule .decline, #confirm_delete .decline, #confirm_return_excerpt .decline, #confirm_create_excerpt .decline",
opengever/meeting/locales/fr/LC_MESSAGES/opengever.meeting.po:msgid "msg_confirm_return_excerpt_dialog"                                        
Binary file opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.mo matches                                                              
opengever/meeting/locales/de/LC_MESSAGES/opengever.meeting.po:msgid "msg_confirm_return_excerpt_dialog"                                        
opengever/meeting/locales/opengever.meeting.pot:msgid "msg_confirm_return_excerpt_dialog"              
```

Comment (jone) [reply opengever/meeting/browser/resources/meeting.js]: 👍
